describe('My first test', () =>{
    it('Adding todos', () =>{
        cy.visit('http://localhost:8080')
        cy.wait(1000)
        cy.get('#add-box').click()
        cy.wait(1000)
        cy.get('.input-todo').type('new todo task')
        cy.wait(1000)
        cy.get('.input-todo').type('{enter}')
        cy.wait(1000)
        cy.get('#add-box').click()
        cy.wait(1000)
        cy.get('.input-todo').type('Ajdo je kralj cypress testova')
        cy.wait(1000)
        cy.get('.input-todo').type('{enter}')
        cy.wait(1000)
        cy.get('#add-box').click()
        cy.wait(1000)
        cy.get('.input-todo').type('Ajdo je kralj bagova')
        cy.wait(1000)
        cy.get('.input-todo').type('{enter}')
        cy.wait(1000)
        cy.get('#add-box').click()
        cy.wait(1000)
        cy.get('.input-todo').type('Ajdo je kralj')
        cy.wait(1000)
        cy.get('.input-todo').type('{enter}')
        cy.wait(1000)
        cy.get('#add-box').click()
        cy.wait(1000)
        cy.get('.input-todo').type('Ajdaho')
        cy.wait(1000)
        cy.get('.input-todo').type('{enter}')
    })
    it('Checking todos', () => {
        cy.wait(1000)
        cy.get(':nth-child(2) > .todo-text > .checkbox').click()
        cy.wait(1000)
        cy.get(':nth-child(3) > .todo-text > .checkbox').click()
        cy.wait(1000)
        cy.get(':nth-child(3) > .todo-text > .checkbox').click()
        cy.wait(1000)
    })
    it('Deleting one todo', () => {
        cy.get(':nth-child(3) > .done-todo-text > #delete_sweeep').click()
        cy.wait(1000)
    })

   it('Should drag one todo to done list', () => {
        cy.get(':nth-child(1) > .todo-text').drag('.flexbox-donelist')
    })

})